/* Generated By:JavaCC: Do not edit this line. LPLParserConstants.java */
package lpl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBR = 8;
  /** RegularExpression Id. */
  int RBR = 9;
  /** RegularExpression Id. */
  int LCBR = 10;
  /** RegularExpression Id. */
  int RCBR = 11;
  /** RegularExpression Id. */
  int LSBR = 12;
  /** RegularExpression Id. */
  int RSBR = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int LSTHN = 17;
  /** RegularExpression Id. */
  int EQUTO = 18;
  /** RegularExpression Id. */
  int FSLSH = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int EXCLAMATION = 25;
  /** RegularExpression Id. */
  int DEF = 26;
  /** RegularExpression Id. */
  int INT = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int BOOLEAN = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int OUTPUT = 32;
  /** RegularExpression Id. */
  int OUTCHAR = 33;
  /** RegularExpression Id. */
  int UNIT = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int RETURN = 36;
  /** RegularExpression Id. */
  int LENGTH = 37;
  /** RegularExpression Id. */
  int NEW = 38;
  /** RegularExpression Id. */
  int ISNULL = 39;
  /** RegularExpression Id. */
  int OP = 40;
  /** RegularExpression Id. */
  int ID = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\"==\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\",\"",
    "\".\"",
    "\"!\"",
    "\"def\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"bool\"",
    "\"if\"",
    "\"output\"",
    "\"outchar\"",
    "\"unit\"",
    "\"while\"",
    "\"return\"",
    "\"length\"",
    "\"new\"",
    "\"isnull\"",
    "<OP>",
    "<ID>",
  };

}
